### ISSUE TITLE
Bad link on "getting started"

### ISSUE THREAD

**Issue by lukasmalkmus** [tremor-rs/tremor-www#317]
Just skimmed the docs and noticed a dead link (`404`). Initially I just thought it was a typo, but it isn't. Let's start from the beginning:

When hitting the "Getting Started" button on https://www.tremor.rs, it sends me to https://www.tremor.rs/docs/0.12/getting-started: The link to `Troy` there is the following, and it returns a `404`: https://www.tremor.rs/docs/language. However, I noticed that all other links which link to the "Getting Started" section (e.g. in the sidebar and top bar) are actually linking to https://www.tremor.rs/docs/0.12/getting-started/ (**notice the trailing `/`**). The `Troy` link there is https://www.tremor.rs/docs/0.12/language. It includes the version and returns the expected page.

No idea what's causing that, I haven't taken a look at the underlying system/engine. Might investigate if I have some time.

Wonder if this is a browser thing. If I hit the link here in the issue, Safari appends `/` to the URL.

**Comment by devskillz47** [comment]
Please close as issue seems to have been solved. The "Troy" link seems work correctly, returning a correct version of the troy docs (https://www.tremor.rs/docs/0.12/language/). The issue was a missing version number from the previous link which made the page unreachable (https://www.tremor.rs/docs/language vs. https://www.tremor.rs/docs/0.12/language/).
